### PR TITLE
Prefix bug fix

### PR DESCRIPTION
**Pull request by awmuncy**
A fix for a bug where the prefix was not updating properly.

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Is this still active? Does it need to be merged?

**Comment by dtbuchholz** [comment]
I'm not sure. I don't recall why it'd be assigned to me—was this something I brought up @awmuncy?

**Comment by carsonfarmer** [comment]
Not sure? I actually suspect it was just supposed to be assigned to you as a reviewer?

**Comment by carsonfarmer** [comment]
Looks 👍

**Review by carsonfarmer — APPROVED** [review]

**Pull request merged**
